version: "3"

services:

  mariadb:
    image: mariadb:10.4.11-bionic
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: rpuser
      MYSQL_PASSWORD: rppassword
      MYSQL_DATABASE: rp
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb_config:/docker-entrypoint-initdb.d/

volumes:
  mariadb_data: